import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "./_component/Footer/page";
import Navbar from "./_component/Navbar/page";
import { Toaster } from "react-hot-toast";

import NextAuthProvider from "./provider/nextAuthProvider";
import Providers from "./provider/react-query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NextAuthProvider>
            <Toaster />
            <Navbar />
            <div className="container m-auto max-w-7xl mt-8 h-min-screen mb-20">
              {children}
            </div>

            <Footer />
          </NextAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
